import qiskit
import qiskit_aer
from qiskit import QuantumCircuit, execute
from qiskit_aer import qasm_simulator, Aer
circ1=QuantumCircuit(2)
circ1.h(0)
circ1.cnot(0,1)
circ2=QuantumCircuit(2)
circ2.x(1)
circ2.h(0)
circ2.cnot(0,1)
circ1.measure_all()
circ2.measure_all()
print(circ1)
print(circ2)
backend=Aer.get_backend('qasm_simulator')
job=backend.run(circ1,shots=1024)
results=job.result()
counts=results.get_counts()
print(counts)
job=backend.run(circ2,shots=1024)
results=job.result()
counts=results.get_counts()
print(counts)
circ1.cnot(0,1)
circ1.h(0)
circ2.cnot(0,1)
circ2.h(0)
circ1.measure_all()
circ2.measure_all()
print(circ1)
print(circ2)
backend=Aer.get_backend('qasm_simulator')
job=backend.run(circ1,shots=1024)
results=job.result()
counts=results.get_counts()
print(counts)
job=backend.run(circ2,shots=1024)
results=job.result()
counts=results.get_counts()
print(counts)